Round the map data
open-sdg/open-sdg pull request #1040
Opened 2020-12-27 06:14 UTC by brockfanning

Fixes #899 

By itself this doesn't change anything, since the [default dataRounding function](https://github.com/open-sdg/open-sdg/blob/master/_includes/javascript-variables.html#L16-L19) does no rounding. But if this rounding function has been customized, this PR applies it to the map data.

2021-01-14 15:47 UTC, jwestw commented
Feature branch created: http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/dynamic-lang-attribute/3-a-1/ 

Testing 3 a 1

2021-01-14 15:54 UTC, jwestw commented
This works. 

**Demonstrating for Scotland 2014 on indicator 3.a.1**

In each case the data is 20.3

![image](https://user-images.githubusercontent.com/67740306/104614724-6bd73280-5680-11eb-81a1-4edfa3051d53.png)

![image](https://user-images.githubusercontent.com/67740306/104614954-a640cf80-5680-11eb-8fc3-8576fe649638.png)


![image](https://user-images.githubusercontent.com/67740306/104615125-d2f4e700-5680-11eb-943a-868c24f60e8e.png)

2021-01-14 15:59 UTC, jwestw commented
Query:

While the rounding is consistent across maps and tables etc. I notice .0 is dropped when the data is an integer. 

![image](https://user-images.githubusercontent.com/67740306/104615474-2ff09d00-5681-11eb-9ff0-234cbad04266.png)


![image](https://user-images.githubusercontent.com/67740306/104615528-3d0d8c00-5681-11eb-926f-84c22660e33e.png)


This makes the rounding consistent between for the same data across maps, tables, and graphs, but not between non-integer data and integer data. I think there is a separate ticket for this issue though.

2021-01-14 16:00 UTC, jwestw commented
Also, rounding is not consistent on the colour scale:

![image](https://user-images.githubusercontent.com/67740306/104615880-937aca80-5681-11eb-8634-4605eaac132e.png)

If there are tickets for this I will find them and insert numbers/links for reference.

2021-01-14 16:01 UTC, jwestw approved these changes
Rounding on the data is consistent for the same data in the various display outputs.

2021-01-14 16:20 UTC, brockfanning commented
@jwestw I think the color-scale was a big part of this request, so since that's not working then I think I need to keep working on this.

2021-01-14 16:21 UTC, jwestw requested changes
Revoking approval according to https://github.com/open-sdg/open-sdg/pull/1040#issuecomment-760290426

2021-01-15 00:01 UTC, brockfanning commented
@jwestw This is ready for another test.

2021-01-19 17:43 UTC, jwestw commented
[This](http://sdgdev-813006012.eu-west-1.elb.amazonaws.com/map-data-rounding/3-a-1/) all looks to be working now. Great stuff.

2021-01-19 17:43 UTC, jwestw approved these changes
Approving according to last comment.

2021-01-19 23:08 UTC, merged